data:
  train_path: data/processed/kepler_lc/train.csv
  test_path: data/processed/kepler_lc/test.csv
  target: label

features:
  numeric: [
    "period_days", "t0", "duration_days", "duration_hours",
    "scale_mean", "scale_std", "scale_skewness", "scale_kurtosis", "scale_outlier_resistance",
    "local_noise", "depth_stability", "acf_lag_1h", "acf_lag_3h", "acf_lag_6h", "acf_lag_12h", "acf_lag_24h",
    "cadence_hours", "depth_mean_per_transit", "depth_std_per_transit", "npts_transit_median",
    "cdpp_3h", "cdpp_6h", "cdpp_12h", "SES_mean", "SES_std", "MES",
    "snr_global", "snr_per_transit_mean", "snr_per_transit_std", "resid_rms_global", "vshape_metric",
    "secondary_depth", "secondary_depth_snr", "secondary_depth_snr_log10", "secondary_depth_snr_capped",
    "secondary_to_primary_ratio", "secondary_is_eb_like", "odd_even_depth_ratio", "ingress_egress_asymmetry",
    "skewness_flux", "kurtosis_flux", "outlier_resistance", "planet_radius_rearth", "planet_radius_rjup"
  ]
  categorical: []

model:
  name: "stacking"
  meta_learner:
    name: "logistic_regression"
    params:
      random_state: 68  # Consistent with trains.py RDS
      max_iter: 1000
      class_weight: "balanced"
      C: 1.0
      solver: "liblinear"

  base_models:
    - "gb"
    - "lgbm"
    - "rf"

artifacts:
  dir: artifacts
  meta_learner_path: artifacts/meta_learner.joblib
  meta_learner_info_path: artifacts/meta_learner_info.json
  stacking_model_path: artifacts/stacking_model.joblib

evaluation:
  test_size: 0.2
  random_state: 68  # Consistent with trains.py RDS
  cv_folds: 5
  threshold_metric: "f1"

sampling:
  use_sampling: false
  smote_strategy: 0.25
  under_strategy: 0.75
  random_state: 68
