// src/config/modelsConfig.ts
export const modelsConfig = {
  "Gradient Boosting": {
    learning_rate: 0.15,
    max_depth: 3,
    max_features: 0.8,
    min_samples_leaf: 10,
    min_samples_split: 10,
    n_estimators: 350,
    n_iter_no_change: 40,
    random_state: 42,
    subsample: 0.75,
    tol: 0.0001,
    validation_fraction: 0.2,
  },
  "LightGBM": {
    random_state: 42,
    n_estimators: 100,
    learning_rate: 0.1,
    max_depth: 5,
    num_leaves: 31,
    min_child_samples: 20,
    subsample: 0.8,
    colsample_bytree: 0.3,
    reg_alpha: 0.0,
    reg_lambda: 0.5,
    metric: ["auc", "average_precision", "binary_logloss"],
    boosting_type: ["gbdt", "dart", "goss"],
  },
  "Random Forest": {
    bootstrap: true,
    class_weight: 0,
    max_depth: 20,
    max_features: 0.5,
    max_samples: 0.8,
    min_samples_leaf: 2,
    min_samples_split: 2,
    n_estimators: 400,
    random_state: 42,
  },
};
