gb:
  learning_rate: 0.15
  max_depth: 3
  max_features: 0.8
  min_samples_leaf: 10
  min_samples_split: 10
  n_estimators: 350
  n_iter_no_change: 40
  random_state: 42
  subsample: 0.75
  tol: 0.0001
  validation_fraction: 0.2
lgbm:
  boosting_type: gbdt
  class_weight: null
  colsample_bytree: 0.3
  learning_rate: 0.1
  max_depth: 5
  metric: auc
  min_child_samples: 20
  n_estimators: 100
  num_leaves: 31
  objective: binary
  random_state: 42
  reg_alpha: 0.0
  reg_lambda: 0.5
  subsample: 0.8
  verbose: -1
rf:
  bootstrap: true
  class_weight: null
  max_depth: 20
  max_features: 0.5
  max_samples: 0.8
  min_samples_leaf: 2
  min_samples_split: 2
  n_estimators: 400
  n_jobs: -1
  random_state: 42
